# TCL File Generated by Component Editor 22.1
# Mon Nov 25 22:54:23 PST 2024
# DO NOT MODIFY


# 
# dotopt_avalon "dotopt_avalon" v1.0
# Aiden O'Leary and Rhys Byers 2024.11.25.22:54:23
# Faster concurrent dot product accelerator,
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module dotopt_avalon
# 
set_module_property DESCRIPTION "Faster concurrent dot product accelerator,"
set_module_property NAME dotopt_avalon
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Personal Accelerators"
set_module_property AUTHOR "Aiden O'Leary and Rhys Byers"
set_module_property ICON_PATH ernie.jpg
set_module_property DISPLAY_NAME dotopt_avalon
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL dotopt
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file dotopt.sv SYSTEM_VERILOG PATH dotopt.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clock
set_interface_property slave associatedReset reset_sink
set_interface_property slave bitsPerSymbol 8
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 0
set_interface_property slave maximumPendingWriteTransactions 0
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave slave_waitrequest waitrequest Output 1
add_interface_port slave slave_address address Input 4
add_interface_port slave slave_read read Input 1
add_interface_port slave slave_readdata readdata Output 32
add_interface_port slave slave_write write Input 1
add_interface_port slave slave_writedata writedata Input 32
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1


# 
# connection point avalon_master_sdram
# 
add_interface avalon_master_sdram avalon start
set_interface_property avalon_master_sdram addressUnits SYMBOLS
set_interface_property avalon_master_sdram associatedClock clock
set_interface_property avalon_master_sdram associatedReset reset_sink
set_interface_property avalon_master_sdram bitsPerSymbol 8
set_interface_property avalon_master_sdram burstOnBurstBoundariesOnly false
set_interface_property avalon_master_sdram burstcountUnits WORDS
set_interface_property avalon_master_sdram doStreamReads false
set_interface_property avalon_master_sdram doStreamWrites false
set_interface_property avalon_master_sdram holdTime 0
set_interface_property avalon_master_sdram linewrapBursts false
set_interface_property avalon_master_sdram maximumPendingReadTransactions 0
set_interface_property avalon_master_sdram maximumPendingWriteTransactions 0
set_interface_property avalon_master_sdram readLatency 0
set_interface_property avalon_master_sdram readWaitTime 1
set_interface_property avalon_master_sdram setupTime 0
set_interface_property avalon_master_sdram timingUnits Cycles
set_interface_property avalon_master_sdram writeWaitTime 0
set_interface_property avalon_master_sdram ENABLED true
set_interface_property avalon_master_sdram EXPORT_OF ""
set_interface_property avalon_master_sdram PORT_NAME_MAP ""
set_interface_property avalon_master_sdram CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master_sdram SVD_ADDRESS_GROUP ""

add_interface_port avalon_master_sdram master_address address Output 32
add_interface_port avalon_master_sdram master_read read Output 1
add_interface_port avalon_master_sdram master_readdata readdata Input 32
add_interface_port avalon_master_sdram master_readdatavalid readdatavalid Input 1
add_interface_port avalon_master_sdram master_waitrequest waitrequest Input 1
add_interface_port avalon_master_sdram master_write write Output 1
add_interface_port avalon_master_sdram master_writedata writedata Output 32


# 
# connection point avalon_master_sram
# 
add_interface avalon_master_sram avalon start
set_interface_property avalon_master_sram addressUnits SYMBOLS
set_interface_property avalon_master_sram associatedClock clock
set_interface_property avalon_master_sram associatedReset reset_sink
set_interface_property avalon_master_sram bitsPerSymbol 8
set_interface_property avalon_master_sram burstOnBurstBoundariesOnly false
set_interface_property avalon_master_sram burstcountUnits WORDS
set_interface_property avalon_master_sram doStreamReads false
set_interface_property avalon_master_sram doStreamWrites false
set_interface_property avalon_master_sram holdTime 0
set_interface_property avalon_master_sram linewrapBursts false
set_interface_property avalon_master_sram maximumPendingReadTransactions 0
set_interface_property avalon_master_sram maximumPendingWriteTransactions 0
set_interface_property avalon_master_sram readLatency 0
set_interface_property avalon_master_sram readWaitTime 1
set_interface_property avalon_master_sram setupTime 0
set_interface_property avalon_master_sram timingUnits Cycles
set_interface_property avalon_master_sram writeWaitTime 0
set_interface_property avalon_master_sram ENABLED true
set_interface_property avalon_master_sram EXPORT_OF ""
set_interface_property avalon_master_sram PORT_NAME_MAP ""
set_interface_property avalon_master_sram CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master_sram SVD_ADDRESS_GROUP ""

add_interface_port avalon_master_sram master2_waitrequest waitrequest Input 1
add_interface_port avalon_master_sram master2_address address Output 32
add_interface_port avalon_master_sram master2_read read Output 1
add_interface_port avalon_master_sram master2_readdata readdata Input 32
add_interface_port avalon_master_sram master2_readdatavalid readdatavalid Input 1
add_interface_port avalon_master_sram master2_write write Output 1
add_interface_port avalon_master_sram master2_writedata writedata Output 32

